config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :customer do
      get 'get_info'
      post 'sign_up'
      post 'sign_in'
      post 'reset_pass'
      post 'update_info'
    end
  end

  resources :devices
  resources :sessions
  resources :customers

  root to: 'visitors#index'
  devise_for :users
  devise_scope :user do
    post "/sessions/user" => 'devise/sessions#create'
  end
  resources :users

  match '*path', via: :all, to: 'api/api#wild'
end

app/models/device.rb
# == Schema Information
#
# Table name: devices
#
#  id         :bigint(8)        not null, primary key
#  category   :string(255)
#  did        :string(255)
#  os         :string(255)
#  model      :string(255)
#  build      :string(255)
#  source     :string(255)
#  user_agent :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Device < ApplicationRecord
  enum category: [:android, :ios, :web, :desktop]

  has_many :sessions
  validates_presence_of :category, :did
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:category, :did, :os, :model, :build, :source, :user_agent)
    end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_with(model: device, local: true) do |form| %>
  <% if device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :did %>
    <%= form.text_field :did %>
  </div>

  <div class="field">
    <%= form.label :os %>
    <%= form.text_field :os %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div class="field">
    <%= form.label :build %>
    <%= form.text_field :build %>
  </div>

  <div class="field">
    <%= form.label :source %>
    <%= form.text_field :source %>
  </div>

  <div class="field">
    <%= form.label :user_agent %>
    <%= form.text_field :user_agent %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing Device</h1>

<%= render 'form', device: @device %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Devices</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Did</th>
      <th>Os</th>
      <th>Model</th>
      <th>Build</th>
      <th>Source</th>
      <th>User agent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= device.category %></td>
        <td><%= device.did %></td>
        <td><%= device.os %></td>
        <td><%= device.model %></td>
        <td><%= device.build %></td>
        <td><%= device.source %></td>
        <td><%= device.user_agent %></td>
        <td><%= link_to 'Show', device %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device', new_device_path %>

app/views/devices/new.html.erb
<h1>New Device</h1>

<%= render 'form', device: @device %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @device.category %>
</p>

<p>
  <strong>Did:</strong>
  <%= @device.did %>
</p>

<p>
  <strong>Os:</strong>
  <%= @device.os %>
</p>

<p>
  <strong>Model:</strong>
  <%= @device.model %>
</p>

<p>
  <strong>Build:</strong>
  <%= @device.build %>
</p>

<p>
  <strong>Source:</strong>
  <%= @device.source %>
</p>

<p>
  <strong>User agent:</strong>
  <%= @device.user_agent %>
</p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>