config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :customer do
      get 'get_info'
      post 'sign_up'
      post 'sign_in'
      post 'reset_pass'
      post 'update_info'
    end
  end

  resources :devices
  resources :sessions
  resources :customers

  root to: 'visitors#index'
  devise_for :users
  devise_scope :user do
    post "/sessions/user" => 'devise/sessions#create'
  end
  resources :users

  match '*path', via: :all, to: 'api/api#wild'
end

app/models/customer.rb
# == Schema Information
#
# Table name: customers
#
#  id         :bigint(8)        not null, primary key
#  email      :string(255)
#  password   :string(255)
#  name       :string(255)
#  mobile     :string(255)
#  country    :string(255)
#  dob        :date
#  address    :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Customer < ApplicationRecord
  has_many :sessions

  validates_presence_of :email, :password
end

app/controllers/api/customer_controller.rb
module Api
  class CustomerController < ApiController

    def sign_up
      raise AuthenticationError
    end

    def sign_in
    end

    def get_info
      he = Customer.first
      obj = {
          email: he.email,
          name: he.name,
          mobile: he.mobile,
          birthday: he.dob,
          kick: CustomerService.kick
      }
      json_response(obj)
    end

    def reset_pass
    end

    def update_info
    end

  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:email, :password, :name, :mobile, :country, :dob, :address)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_with(model: customer, local: true) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :mobile %>
    <%= form.text_field :mobile %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :dob %>
    <%= form.date_select(:dob, start_year: Date.today.year - 100, end_year: Date.today.year - 18 )%>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password</th>
      <th>Name</th>
      <th>Mobile</th>
      <th>Country</th>
      <th>Dob</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.email %></td>
        <td><%= customer.password %></td>
        <td><%= customer.name %></td>
        <td><%= customer.mobile %></td>
        <td><%= customer.country %></td>
        <td><%= customer.dob %></td>
        <td><%= customer.address %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @customer.password %>
</p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @customer.mobile %>
</p>

<p>
  <strong>Country:</strong>
  <%= @customer.country %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @customer.dob %>
</p>

<p>
  <strong>Address:</strong>
  <%= @customer.address %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>